GET http://localhost:8080/spring-mvc-app/api/v1/user/all

###

GET http://localhost:8080/spring-mvc-app/api/v1/user/1

###

POST http://localhost:8080/spring-mvc-app/api/v1/user
Content-Type: application/json

{
  "username": "user88",
  "password": "qwer",
  "email": "user88@mail.com",
  "age": 9
}

###

PUT http://localhost:8080/spring-mvc-app/api/v1/user/1

###

DELETE http://localhost:8080/spring-mvc-app/api/v1/user/1